### ISSUE TITLE
[RELEASE] 11.7.1

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#1037] opened 2021-09-15 12:33 UTC
Release a new version

Xcode version to work with:
12.5.1

### Git & Code

- [x] [GIT] Create branch `release/[major].[minor].[patch]` (freeze the code)
- [x] [DEV] Update `APP_SHORT_VERSION` `[major].[minor].[patch]` in [ownCloud.xcodeproj/project.pbxproj](https://github.com/owncloud/ios-app/blob/master/ownCloud.xcodeproj/project.pbxproj)
- [ ] [TRFX] Update translations from transifex branch.
- [ ] [TRFX] Check for missing translations. Ping @cscherm
- [x] [DIS] Update [changelog](https://github.com/owncloud/ios-app/blob/master/CHANGELOG.md)
- [x] [DEV] Update In-App Release Notes (changelog) in ownCloud/Release Notes/ReleaseNotes.plist
- [x] [DEV] Changelog: Created a folder for the new version like $majorVersion.$minorVersion.$patchVersion_YYYY-MM-DD
- [x] [DEV] Changelog: Moved all changelog files from the unreleased folder to the new version folder
- [x] [QA] Design Test plan
- [x] [QA] Regression Test plan
- [ ] [DOC] Update user manual with the new functionalities
- [ ] [DOC] Update owncloud.org/download version numbers (notify #wordpress)
- [ ] [GIT] Merge branch `release/[major].[minor].[patch]` in master
- [ ] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [ ] [GIT] Add the new release on [GitHub ios-app](https://github.com/owncloud/ios-app/releases)

If it is required to update the iOS-SDK version:

- [x] [GIT] Create branch library `release/[major].[minor].[patch]`(freeze the code)
- [ ] [mail] inform #marketing about the new release.
- [ ] [DIS] Update README.md (version number, third party, supported versions of iOS, Xcode)
- [ ] [DIS] Update [changelog](https://github.com/owncloud/ios-sdk/blob/master/CHANGELOG.md)
- [ ] [GIT] Merge branch `release/[major].[minor].[patch]` in `master`
- [ ] [GIT] Create tag and sign it `[major].[minor].[patch]`
- [ ] [GIT] Add the new release on [GitHub ios-sdk](https://github.com/owncloud/ios-sdk/releases)

If it is required to update third party:

- [ ] [DIS] Update THIRD_PARTY.txt

## App Store

- [x] [DIS] App Store Connect: Create a new version following the `[major].[minor].[patch]`
- [ ] [DIS] App Store Connect: Trigger Fastlane screenshots generation and upload
- [ ] [DIS] Upload the binary to the App Store
- [ ] [DIS] App Store Connect: Trigger release (manually)
- [ ] [DIS] App Store Connect: Decide reset of iOS summary rating (Default: keep)
- [ ] [DIS] App Store Connect: Update description if necessary (coordinated with #marketing)
- [ ] [DIS] App Store Connect: Update changelogs
- [ ] [DIS] App Store Connect: Submit for review

## BUGS & IMPROVEMENTS:

- [X] (1) Crashes when many Photos/Videos are uploaded https://github.com/owncloud/ios-app/issues/1037#issuecomment-922696991 [FIXED]

**Comment by jesmrec** [comment] 2021-09-20 07:39
### (1)

1. Open oC and click on "+"
2. Select "Upload From your Photo library"
3. Select 50 Photos/Videos (orientative number, also reproducible with more or less items)

Current behaviour:

app crashes several times during the process

https://user-images.githubusercontent.com/14894746/133969028-4587ac2a-6be3-4fea-95fc-444aa095b2f3.MP4

Expected:

no crashes and everything uploaded

Logs caught:

[ownCloud_20_Sep_2021_at_09_36_27.log.txt.zip](https://github.com/owncloud/ios-app/files/7194215/ownCloud_20_Sep_2021_at_09_36_27.log.txt.zip)


iPhone XR iOS 14.8
`806488dca`

**Comment by felix-schwarz** [comment] 2021-09-20 10:04
@jesmrec Looks like the SDK used was too old and didn't include the fix for the crash bug that seems responsible here. I updated the SDK with the latest `milestone/11.7.1` commit. Please check if it also fixes the issue for you.

**Comment by jesmrec** [comment] 2021-09-20 10:49
@felix-schwarz the SDK update fixed the problem.

**Comment by hosy** [comment] 2021-09-20 12:03
@jesmrec does it also fixed the other issues? 

https://github.com/owncloud/ios-app/issues/1039
https://github.com/owncloud/ios-app/issues/1025
https://github.com/owncloud/ios-app/issues/1024

**Comment by jesmrec** [comment] 2021-09-20 12:13
> @jesmrec does it also fixed the other issues?
> 
> #1039
> #1025
> #1024

unfortunately, not fixed with `32d0216d1` and iOS15.0

**Comment by jesmrec** [comment] 2021-09-21 11:45
> @jesmrec does it also fixed the other issues?
> 
> #1039
> #1025
> #1024

fixed with the latest iOS update

**Comment by jesmrec** [comment] 2021-09-21 14:34
## QA

Most of the new stuff is oriented to customers and branding, not for App Store release. 

Fixes for PDF viewer and iOS15 are the topic in the current App Store version. For this reason, regression will be reduced to speed up the release after the iOS15 release.

QA checks (iOS15 & iOS14):

- [X] Basic auth (positive & negative)
- [X] OAuth2 auth (positive & negative)
- [X] OIDC auth (positive & negative)
- [X] Transfers (uploads & downloads)
- [X] File previews (including PDF viewer)
- [X] Sharing with oC
- [X] Files App basic checks

Other basic operations were tested with the [E2E tests](https://github.com/owncloud/ios-scenario-testing/tree/master/src/test/resources/io/cucumber):

Serenity report: 
[serenity_iOS11.7.1_20210921.zip](https://github.com/owncloud/ios-app/files/7202795/serenity_iOS11.7.1_20210921.zip) ✅ 

Upgrade test (from 11.7)

- [ ] iOS14.8
- [ ] iOS15.0
- [X] Upgrade from iOS14 to iOS15

____

## Final report

Xcode version: `12.5.1 (12E507)`

Approved commits:

app: 
sdk: 

Devices used:

IPhoneXR iOS 14.8
iPhoneXs iOS 15.0
iPadAir iPadOS 14.8

**Closed** 2021-09-22 07:15 UTC
