### ISSUE TITLE
OAuth 2.0 end-to-end experience

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#267] opened 2019-02-10 11:41 UTC
Screenshot 1 | Screenshot 2 | Screenshot 3 | Screenshot 4
-- | -- | -- | --
![image](https://user-images.githubusercontent.com/214010/52532903-360ad000-2d2c-11e9-895f-0fcbb5ca18b5.png) | ![image](https://user-images.githubusercontent.com/214010/52532906-40c56500-2d2c-11e9-9840-67e6957c7132.png) | ![image](https://user-images.githubusercontent.com/214010/52532913-4fac1780-2d2c-11e9-8964-412d3575858d.png) | ![image](https://user-images.githubusercontent.com/214010/52532924-5c307000-2d2c-11e9-891e-a25efbc879a8.png)

### Problem 1

- Regular users don't understand why the 2nd screen (see **Screenshot 1**) after entering the server URL is useful
- We could explain this feature, and users should have an option to skip this screen in the future

@felix-schwarz @mneuwert @hosy 

### Problem 2

- Name of the app is different
- In the warning message, it says `"ownCloud" Wants to Use…` (see **Screenshot 2**)
- The OAuth 2.0 login screen says `The application "iOS" is requesting…` (see **Screenshot 3** &  **Screenshot 4**)

@DeepDiver1975 we should rename it in the OAuth 2.0 app to "ownCloud iOS app".

@felix-schwarz Any chance it could say "ownCloud app" or "ownCloud iOs app" in the warning message?

### Steps to reproduce
1. Install [OAuth 2.0 master (`40fe0ab`)](https://github.com/owncloud/oauth2/tree/40fe0abf6ff63e97f9e79ad9f2969314bd1d0144) on ownCloud server
2. Add account to the ownCloud iOS app

### Client
**iOS version:**
iOS 12.1.4 (16D57)

**ownCloud app version:**
ownCloud beta version 1.0 build 105 (https://github.com/owncloud/ios-app/tree/b19e57b2f67234460ae6dec8f9587d62ed34d2f0, built from branch)

**Device model:**
Model: iPhone XS Max

### Server configuration

**ownCloud version:**
ownCloud server 10.1.0 with master-[OAuth 2.0 (`40fe0ab`)](https://github.com/owncloud/oauth2/tree/40fe0abf6ff63e97f9e79ad9f2969314bd1d0144) on ownCloud server

/cc @hodyroff

**Comment by hosy** [comment] 2019-02-21 09:16
> ### Problem 1
> * Regular users don't understand why the 2nd screen (see **Screenshot 1**) after entering the server URL is useful
> * We could explain this feature, and users should have an option to skip this screen in the future
> 
> @felix-schwarz @mneuwert @hosy
> 
This is happening because OAuth2 uses SFAuthenticationSession by default instead of SFSafariViewController. There is unfortunately nothing we can do at the moment to either change or remove these alerts when using SFAuthenticationSession.

**Comment by michaelstingl** [comment] 2019-02-21 09:20
@hosy Problem 1 ==> Screenshot 1. This isn't about the alert popping up.

**Comment by hosy** [comment] 2019-02-21 09:24
> @hosy Problem 1 ==> Screenshot 1. This isn't about the alert popping up.

Maybe this have something to do with the server certificate. I think @felix-schwarz could have an answer for this step.

**Comment by hosy** [comment] 2019-02-22 10:35
@michaelstingl a possible solution could look like this examples:

- More details for certificate validation 
- Explanation for the user, why an alert will be shown in the next step

| Certificate passed validation                                                                                                                                     | Certificate validation failed                                                                                                                                     |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| ![simulator screen shot - iphone xr - 2019-02-22 at 11 29 07](https://user-images.githubusercontent.com/736109/53236845-90455280-3695-11e9-9994-d61dfa5dcc8f.png) | ![simulator screen shot - iphone xr - 2019-02-22 at 11 31 52](https://user-images.githubusercontent.com/736109/53236847-90455280-3695-11e9-938c-7da00ec25471.png) |

**Comment by michaelstingl** [comment] 2019-02-22 10:58
@hosy Yeah, I like! 👍  But: color as only differentiator doesn't work for colorblind user.

**Comment by hosy** [comment] 2019-03-18 16:08
@michaelstingl here you can see a new draft for this view. 
- Certificate state is shown in `Certificate Details` row
- Short explanation for the certificate state as footer text
- Info panel as footer view to give the user a description for the next oAuth step

| Certificate passed validation                                                                                                                                     | Certificate validation failed                                                                                                                                     |
|-------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| ![Simulator Screen Shot - iPhone X - 2019-03-18 at 17 02 15](https://user-images.githubusercontent.com/736109/54544474-06408f00-49a0-11e9-9bcd-6a240135c0a8.png) | ![Simulator Screen Shot - iPhone X - 2019-03-18 at 17 04 36](https://user-images.githubusercontent.com/736109/54544514-1fe1d680-49a0-11e9-8b6e-e472393a998b.png) |

**Comment by michaelstingl** [comment] 2019-03-18 22:24
> Left screenshot has info panel on top

My gut feeling would favorite the left one (info on top)

**Comment by jesmrec** [comment] 2019-03-20 14:23
Let's go with a bit of QA here

**Comment by jesmrec** [comment] 2019-03-20 14:32
In the message to clarify the warning, there is a small typo.

`"If you 'Continue', you will be prompted to allow the '%@' App to open OAuth 2 login where you can enter your credentials."`

"OAuth 2"  => "OAuth2"

**Comment by jesmrec** [comment] 2019-03-20 14:44
If the server is `http` with `OAuth2`, there is no intermediate step, so the new warning is displayed at the same time as the alert, because no certificate is required:

![Mar-20-2019 15-41-06](https://user-images.githubusercontent.com/14894746/54693291-a0324400-4b26-11e9-9634-118df28a3fad.gif)

Should we include something in the flow to stop the alert before?

**Comment by jesmrec** [comment] 2019-03-20 14:54
About the OCCertificate color labels,  i can reproduce `Error`, `Passed`, `Warning` and `Accepted`. But `Rejected`, i do not find steps to get it. Any idea?

**Comment by hosy** [comment] 2019-03-20 15:03
@jesmrc I don’t know how to force Rejected. 
I am not sure how to handle the http step. Maybe we should include an additional step!? @michaelstingl

**Comment by jesmrec** [comment] 2019-03-20 15:08
about the statuses, i will add more UI tests to cover all options.

**Comment by hosy** [comment] 2019-03-20 20:12
@jesmrec is there a public OC server with OAuth2 and http for testing?

**Comment by jesmrec** [comment] 2019-03-21 07:34
no, afaik. But you can create a docker in this way:

1. Create the container:
`docker run -name OAuth2container -p 15000:8080 owncloud/server:10.1`

2. Install and enable OAuth2 inside:
`docker exec -ti OAuth2container bash -l`
`cd apps`
`git clone https://github.com/owncloud/oauth2.git` 
`../occ app:enable oauth2`

Maybe, there are another "scripted" way to do it.

**Comment by jesmrec** [comment] 2019-03-21 12:39
typo is fixed. i will address the tests in a separate issue. When `http` issue is done, please ping me to check and move it forward.

**Comment by michaelstingl** [comment] 2019-03-21 12:45
> 2\. Install and enable OAuth2 inside:
>     `docker exec -ti OAuth2container bash -l`

You don't need to exec into the Docker to install apps:
https://github.com/owncloud-docker/base#available-environment-variables

**Comment by michaelstingl** [comment] 2019-03-21 12:46
> I am not sure how to handle the http step. Maybe we should include an additional step!? @michaelstingl

Missing SSL should also trigger a cert warning 😱  /cc @felix-schwarz

**Comment by jesmrec** [comment] 2019-03-21 13:57
> You don't need to exec into the Docker to install apps:
https://github.com/owncloud-docker/base#available-environment-variables

thanks for the tip!!

**Comment by felix-schwarz** [comment] 2019-03-21 20:09
> > I am not sure how to handle the http step. Maybe we should include an additional step!? @michaelstingl
> 
> Missing SSL should also trigger a cert warning 😱 /cc @felix-schwarz

Unless the user enters a URL starting with `http://`, the SDK will pre-pend `https://`, so it takes extra effort on behalf of the user to enter `http://`. That's why it currently doesn't respond to it with an issue.

I think we have several options here:
- handle the `http://`-case fully inside the app (which would then bring up an alert on its own)
- handle the `http://`-case inside the SDK, which should require little to no changes in the app.

If we pick the SDK-option, I'd also like to add an OCClassSettings/MDM option `HTTPURLPolicy` with these possible options:
- `allow` (would be present state: no warning)
- `warn` (would turn a `http`-URL into a warning as proposed)
- `forbidden` (would turn a `http`-URL into an error, so no bookmark can be created for it)

**Comment by hosy** [comment] 2019-03-21 21:14
@felix-schwarz I like the SDK-option, because it is fixed inside the SDK and cannot be removed. It is more secure by default.
I also like to implement your suggestion with the possible options. But we should show always an warning, if a http:// server is entered. Maybe `allow` should also the same like `warn`.

**Comment by felix-schwarz** [comment] 2019-03-22 08:23
@hosy I agree. `warn` should be the default. But `allow` as a distinct option is useful for keeping unit tests / testing simple. Some tests would otherwise have to choose between supplying their own certificate - or handling the warning.

**Comment by felix-schwarz** [comment] 2019-03-22 21:35
@hosy Just pushed the SDK-implementation and some necessary app-changes in https://github.com/owncloud/ios-sdk/commit/89f5b7baa8ae990ccdb5a86933bfc4e0eddeca66 and #328 respectively.

**Comment by hosy** [comment] 2019-03-23 21:45
@jesmrec for http I added an additional step to show the OAuth info text, before the OAuth authentication process is performed. There is now one step more for http connections, but this should be rare, because https should be the standard.
I also linked against the newest SDK version 
https://github.com/owncloud/ios-sdk/commit/89f5b7baa8ae990ccdb5a86933bfc4e0eddeca66

**Closed** 2019-03-26 20:29 UTC
Labels: Design, Estimation - 3 (M), Login, p2-high
