### ISSUE TITLE
[BUG] @webzit 's issue with iOS Files app

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#1239] opened 2023-07-04 13:41 UTC
@webzit I messed up with the log files and screen recording by mixing issues, users, mail, central forum whatever. Please help us better understand your problem by uploading app debug logs and screen recording from the same time here:
https://cloud.owncloud.com/s/jCKjAqS5ZhCskWH

@felix-schwarz please access internally here:
https://cloud.owncloud.com/f/6025928

**Comment by webzit** [comment] 2023-07-13 20:52
This is the same bug report as https://github.com/owncloud/ios-app/issues/1245 


ownCloud team can access the logs internally here:
https://cloud.owncloud.com/f/6030163

**Comment by felix-schwarz** [comment] 2023-07-24 07:35
Thanks. Closing this as a duplicate of #1245 then.

**Closed by felix-schwarz** 2023-07-24 07:35 UTC
