### ISSUE TITLE
Changes in Files app don't propagate to ownCloud app

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#204] opened 2019-01-13 16:05 UTC
### Steps to reproduce
1. Perform steps from https://github.com/owncloud/ios-app/issues/203 in iOS Files app
2. Create folder "Test" in root ==> ownCloud app doesn't show change
3. Rename folder "Test" to "Test2" ==> ownCloud app doesn't show change
4. Pull-to-refresh in the ownCloud app ==> Folder "Test2" appears

Step 2. | Step 3. | Step 4.
-- | -- | --
![2019-01-13 16 51 13](https://user-images.githubusercontent.com/214010/51087567-480d4900-1755-11e9-8286-be737d22255c.png) | ![2019-01-13 16 52 34](https://user-images.githubusercontent.com/214010/51087568-48a5df80-1755-11e9-842c-c4bf486622ef.png) | ![2019-01-13 16 52 46](https://user-images.githubusercontent.com/214010/51087569-48a5df80-1755-11e9-94ac-a4bcc1d526b2.png)

### Expected behaviour
ownCloud app should poll for changes.

### Actual behaviour
Changes in Files app don't propagate to ownCloud app

### Client
**iOS version:**
iOS 12.1.3 (16D5039a)

**ownCloud app version:**
ownCloud beta version 1.0 build 96 (https://github.com/owncloud/ios-app/commit/c5c74efd5850c2279ee42b057ca0332696da1569, not shown in the app??)

**Device model:**
Model: iPad Pro (10.5-inch) (Model A1709, A1852)

**Comment by felix-schwarz** [comment] 2019-01-15 13:34
This is fixed as of 
https://github.com/owncloud/ios-app/pull/167/commits/3266cfa7acc89ad5676497b24fb7fec814500d82.

**Comment by jesmrec** [comment] 2019-01-16 12:44
Checked the following operations to propagate (commit `3266cfa`)

- [ ] Create a folder: small glitch with folder duplication till pull down is done:


![ezgif com-optimize](https://user-images.githubusercontent.com/14894746/51248850-b76f7c80-1991-11e9-8873-e5948c225991.gif)


- [X] Rename an item -> OK

- [ ] Duplicate an item: same effect like creating folder. By pulling down, ownCloud app crashes:

![jan-16-2019 13-39-51](https://user-images.githubusercontent.com/14894746/51249666-3f568600-1994-11e9-975e-41c2765710b9.gif)


- [ ] Move an item: Needed a refresh to propagate

- [ ] Delete an item: Needed a refresh to propagate

**Comment by felix-schwarz** [comment] 2019-01-17 09:04
@jesmrec Thanks, I'll look into it! Which version of iOS is this happening with?

**Comment by jesmrec** [comment] 2019-01-17 09:32
iOS 12.1, i used an iPad Air

**Comment by felix-schwarz** [comment] 2019-01-17 11:17
@jesmrec I fixed a couple of issues in https://github.com/owncloud/ios-app/pull/167/commits/bbe8915b477cfa06ab996d9ec78b31af6ab63144, ending up with this status:
- Create a folder: now without visual glitch
- Duplicate an item: works for files, there seems to be an issue with folders that I'll need to check seperately
- Delete an item: properly propagates
- Move an item: works for updating the target folder, doesn't propagate removal from source folder yet (I'm on it)

**Comment by felix-schwarz** [comment] 2019-01-17 11:49
@jesmrec As of https://github.com/owncloud/ios-app/pull/167/commits/04463001e5307f72bc33f823181234eb12313120, moves propagate properly now, ending up with this status:
- Create a folder: properly propagates
- Duplicate an item: works for files, there seems to be an issue with folders that I'll need to check seperately
- Delete an item: properly propagates
- Move an item: properly propagates

**Comment by jesmrec** [comment] 2019-01-17 11:50
let's check it!

**Comment by jesmrec** [comment] 2019-01-17 14:13
Create a folder and Delete item -> fixed.

Move has more test cases, i'm on it

**Comment by jesmrec** [comment] 2019-01-18 14:01
latest tests over : eb5f074bf702173e59852bd6a718f3d1ad787c31

**Propagation Files App -> App**

- Duplication of folders: get stucked
- Copy a file and paste in a different folder: get stucked
- Creation of folders works fine, but sometimes the glitch here appears: https://github.com/owncloud/ios-app/issues/204#issuecomment-454766235

**Propagation App -> Files App**

All operations work, but the creation of the folder not always work. Looking for some steps.

**Comment by felix-schwarz** [comment] 2019-01-20 16:05
@jesmrec Thanks for the testing and feedback!

I've since made many more changes to the SDK to hopefully address the remaining glitches (especially around remote changes not propagating).

I've also added verbose logging to the File Provider actions (like createDir, delete, import, ..) so that it's now possible to see how iOS invoked an action and – using a UUID – follow the action along and see how it concluded.

Using that, I took a look at what happens with duplication of folders. Here's what I found. If you duplicate the "Photos" folder in the root directory, iOS will:
1) try to create another "/Photos" folder, which fails with "item already exists"
2) create a "/Photos 2" folder, which succeeds
3) download "/Photos/Paris.jpg"
4) upload "Paris.jpg" to "/Photos 2"
5) create "/Photos 2/Photos"
6) download "/Photos/Paris.jpg"
7) upload "Paris.jpg" to "/Photos 2/Photos"
8) create "/Photos 2/Photos/Photos"
9) download "/Photos/Paris.jpg"
10) upload "Paris.jpg" to "/Photos 2/Photos/Photos"
…
x) create "/Photos 2/Photos/Photos/Photos/Photos/Photos"
x+1) download "/Photos/Paris.jpg"
x+2) upload "Paris.jpg" to "/Photos 2/Photos/Photos/Photos/Photos/Photos"
…
iOS will repeat this action until the FileProvider dies of memory starvation.

From what I can see, the FileProvider reacts correctly to every command from iOS, but the commands from iOS are bogus. This does not look like something we can fix from the FileProvider side, unfortunately.

Curious, I took a look at what happens when using the DropBox file provider:
- a lot of "flashing" here simply moving files around 😜
- it seems that the DB file provider returns a custom error when trying to create a folder that already exists instead of the `[NSError (NSFileProviderError) fileProviderErrorForCollisionWithItem:]` that Apple asks to be returned in the docs and header files.
- that custom error opens a prompt and effectively prevents the usage of "Duplicate"

I then also checked one of probably the best FP implementations in Working Copy:
- using "Duplicate" on a folder there briefly brings up a placeholder by the same name, and then just stops and removes the placeholder again
- in effect, duplication doesn't seem to be possible there, either

**Comment by michaelstingl** [comment] 2019-01-21 12:55
@jesmrec Open new issues?

**Comment by jesmrec** [comment] 2019-01-21 14:12
in case of the duplication, as @felix-schwarz commented, it is a matter of iOS. About the copy/paste, if the issue is not related, we can address to another issue.

**Comment by jesmrec** [comment] 2019-01-25 07:42
moving the current status to #233

**Closed by jesmrec** 2019-01-25 07:42 UTC
Labels: bug, feature: file operation, feature:fileList, feature:filesApp, fixed-in-branch, p2-high, sdk-involved
