### ISSUE TITLE
[FEATURE REQUEST] Japanese(2-Byte character) input support

### ISSUE THREAD

**Issue by Bables55** [owncloud/ios-app#916] opened 2021-03-04 01:25 UTC
**Is your feature request related to a problem? Please describe.**
When users take a picture with the "Scan Document" function and enter the file name, there is a problem with entering Japanese (2-byte characters).
I've written about it in my forum, including the current issues, so please take a look there as well.
https://central.owncloud.org/t/support-for-2-byte-characters-in-scan-document/29856

**Describe the solution you'd like**
I want to use Japanese (2-byte characters) in file names without any problems.

**Describe alternatives you've considered**
The only way to solve this problem is to use 1-byte characters.

**Additional context**
1: https://od.lk/s/M18yNDA3ODk3NDdf/oc-flickjapanese.MP4 2
2: https://od.lk/s/M18yNDA3ODg4ODNf/oc-qwertyjapanese.mp4

### TASKS

- [ ] Research (if needed)
- [ ] Create branch feature/feature_name
- [ ] Development tasks
  - [ ] Implement whatever
  - [ ] ...
- [ ] Code review and apply changes requested
- [ ] Design test plan
- [ ] QA
- [ ] Merge branch feature/feature_name into master

### PR

- App
- Library (if needed)

**Comment by hosy** [comment] 2021-03-12 12:11
@Bables55 thank you for reporting this bug. 
The problem is fixed now and will be available with next version 11.6.

**Comment by jesmrec** [comment] 2021-03-24 16:20
Done

**Closed by jesmrec** 2021-03-24 16:20 UTC
Labels: bug, p2-high
