### ISSUE TITLE
[BUG] Status keeps download even if I already removed it (and many times)

### ISSUE THREAD

**Issue by cdamken** [owncloud/ios-app#621] opened 2020-02-19 16:25 UTC
### Steps to reproduce
1. Download a big file (never finished to download)
2. Remove the file for downloading
3. Go to Status window:

![IMG_0001](https://user-images.githubusercontent.com/7264495/74852015-535d7b80-533c-11ea-9ec4-83df30a9c076.PNG)

### Expected behavior
Status is Clean

### Actual behavior
See above picture

### Client
**iOS version:**
Latest and greatest

**ownCloud app version:**
Latest and greatest

**Device model:**
IPAD

### Server configuration
**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.3

**ownCloud version:**
10.3.2

**Storage backend (external storage):**
WND (Not used for this issue)

### Logs

[ownCloud_19._Feb_2020_at_16_18_10.log.txt.zip](https://github.com/owncloud/ios-app/files/4226033/ownCloud_19._Feb_2020_at_16_18_10.log.txt.zip)

#### Web server error log
```
No errors
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

**Comment by cdamken** [comment] 2020-03-10 18:31
And 20 days later:

![C5149E08-E242-4612-8328-3ECF1FF01F90](https://user-images.githubusercontent.com/7264495/76346699-0b8e9c00-62cb-11ea-8231-42a2a228161a.png)

**Comment by cdamken** [comment] 2020-03-10 18:46
@michaelstingl Do you need more Information ?

**Comment by cdamken** [comment] 2020-03-11 17:29
![DA6A8CB5-14EB-468D-85C5-82C30568D2A2](https://user-images.githubusercontent.com/7264495/76445622-5243cb00-638b-11ea-817b-d744588aba59.png)

Testen with the new version 1.3.1 and after one hour is the same behavior.

**Comment by cdamken** [comment] 2020-03-11 18:40
Now it added a new process:

![30A931DC-E324-4961-BAB1-DC3CD3132B4D](https://user-images.githubusercontent.com/7264495/76451750-8a500b80-6395-11ea-85f0-a47e20781773.png)

**Comment by cdamken** [comment] 2020-03-11 18:47
I’m wondering if the delete process is stopped because of some scanning.

I tried to go into another folder “Media” and then delete another file.

10 Minutes later the file is still not deleted:

![806667E5-2B71-4A9B-B1A7-1CC535E22E1C](https://user-images.githubusercontent.com/7264495/76452240-6ccf7180-6396-11ea-816d-79d464e09d5a.png)

**Comment by hosy** [comment] 2020-03-12 19:57
@felix-schwarz please can you have a look?

**Comment by felix-schwarz** [comment] 2020-03-16 10:18
@cdamken It's only blocked if it's in state `Pending`. It is being executed when in state `Running`.

The entry for `Joker.mp4` seems to still be the one from when you filed the issue originally. If you retry the same steps with a different file now, with `1.3.1`, can you still reproduce the issue?

**Comment by felix-schwarz** [comment] 2020-03-23 20:40
@cdamken Spent some time analyzing the log and found this:
- since background transfers are broken under iOS 13, the app can currently only transfer data in the foreground (+ 30 seconds in the background), at which point the download is cut off by iOS.
- the app then tries to resume the download to eventually download the entire file
- the log comes from version 1.3.0, which still had a metadata bug corrupting state when several downloads were initiated against the same file at the same time
- a consequence of that likely also is that the deletion of the item won't finish

Can you please retry with a newly created bookmark and version `1.3.1`? The problem should no longer occur there.

---

Background downloads continue to work under iOS 13 when using the Files app. So if you'd like to download a large file in the background, please use the Files app until Apple fixes the background transfer bug that currently keeps the app from using it.

**Comment by cdamken** [comment] 2020-03-23 20:52
The `Deleting Carlolina-FLIX...` was newly created with `1.3.1`and now 12 days later the screen looks like https://github.com/owncloud/ios-app/issues/621#issuecomment-597804935

**Comment by michaelstingl** [comment] 2020-03-23 23:02
@cdamken you need to delete the account, then login again. Sorry for the inconvenience.

**Comment by cdamken** [comment] 2020-04-20 14:56
I try to remove the account, it keeps saying that is locked.

I will continue trying to remove the account

**Comment by michaelstingl** [comment] 2020-04-20 20:28
@cdamken please delete the app, the reinstall. Sorry, this is really fucked up.

**Comment by felix-schwarz** [comment] 2020-04-27 07:51
Closing as @cdamken reported he no longer can reproduce the issue with version 1.3.2.

**Comment by cdamken** [comment] 2020-04-27 07:51
I deleted the app, started again from the beginning, took about 4 days to do the scan but now I can see any issues, I think we can close this and create a new one later

**Closed by felix-schwarz** 2020-04-27 07:51 UTC
