### ISSUE TITLE
[BUG] Extra Padding for Rename Action in More Card

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#649] opened 2020-03-18 08:28 UTC
## If you found a bug:

I saw an extra padding on the left of the "Rename" action in the context menu (by @PVince81)

![IMG_0046 PNG](https://user-images.githubusercontent.com/736109/76940569-cab20b00-68fa-11ea-8476-86df71dbedda.jpeg)

### Steps to reproduce
1. Open `More` Card
2. Look at `Rename` Action

### Expected behaviour
All titles have the same spacing on the left.

### Actual behaviour
Rename action has an extra padding on the left

### Client
**ownCloud app version:**
1.3.1

**Comment by felix-schwarz** [comment] 2020-03-28 15:29
I couldn't reproduce this with what's in `release/1.3.2`.

**Comment by felix-schwarz** [comment] 2020-04-07 19:23
Turns out it was an extra space in the translation files:

`"Move" = "[extra space]Move";`

Fixed in #b19adc6.

**Closed** 2020-04-08 20:27 UTC
Labels: UX
