### ISSUE TITLE
[BUG] [iOS12] Share Sheet broken in iOS 12

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/ios-app#782] opened 2020-08-24 19:51 UTC
### Steps to reproduce
1. Open iOS Photos app
2. Share image file
3. Choose "Share to ownCloud" ==> Buttons `[Save here]` and `[Cancel]`are unresponsive, only force-quit of the iOS Photos App help

![IMG_0003](https://user-images.githubusercontent.com/214010/91091700-46a54180-e657-11ea-9ed4-be116eb8b9d0.PNG) | ![IMG_0004](https://user-images.githubusercontent.com/214010/91091713-4c028c00-e657-11ea-8f72-bc5f5833e343.PNG)
-- | --

### Expected behavior
Share Sheet should also work in iOS 12

### Actual behavior
Share Sheet buttons are are unresponsive

### Client
**iOS version:**
12.4.7 and 12.4.8

**ownCloud app version:**
App Store 11.4 build 169 (app: ea77ff3f, sdk: 2de9cbf)

**Device model:**
iPhone 5s and iPad mini 2

### Server configuration
**ownCloud version:**
```
% curl https://demo.owncloud.com/status.php | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   155  100   155    0     0    637      0 --:--:-- --:--:-- --:--:--   637
{
  "installed": true,
  "maintenance": false,
  "needsDbUpgrade": false,
  "version": "10.4.1.3",
  "versionstring": "10.4.1",
  "edition": "Enterprise",
  "productname": "ownCloud"
}
```

**Comment by michaelstingl** [comment] 2020-08-24 19:52
No problems found in iOS 13 and iOS 14 beta5

**Comment by felix-schwarz** [comment] 2020-08-24 20:11
It looks like the issue is rooted here:

```swift
	@objc private func selectButtonPressed() {
		dismiss(animated: true, completion: {
			self.userChose(item: self.query.rootItem)
		})
	}
```

`.dismiss()` never calls the completion handler if the view controller - likely because it hasn't been presented on iOS 12, just pushed on the navigation controller. I'll take a closer look.

**Comment by felix-schwarz** [comment] 2020-08-24 20:29
Ok, this should now be fixed as of 5bb5e85d20187b1fcf46769ae4ea0d55f82c67cc.

**Comment by michaelstingl** [comment] 2020-08-31 08:56
included in `milestone/11.4.1` branch

**Comment by jesmrec** [comment] 2020-09-01 10:53
Checking the fix with commit `47d0dd87``

- `Save` button works fine ✅ 
- `Cancel` button stills unresponsive ❌ 

iOS12.4
Simulator iPhone7

**Comment by felix-schwarz** [comment] 2020-09-09 20:47
@jesmrec Fixed as of https://github.com/owncloud/ios-app/commit/29b2440058676b2df06424b75e60eb0aa024ca70

**Comment by jesmrec** [comment] 2020-09-10 07:03
Fixed and approved

**Comment by jesmrec** [comment] 2020-09-14 06:29
Ready to 11.4.1

**Closed by jesmrec** 2020-09-14 06:29 UTC
Labels: Approved by QA, bug, iOS 12
