### ISSUE TITLE
Server certificate approval is shown after it was approved

### ISSUE THREAD

**Issue by hosy** [owncloud/ios-app#226] opened 2019-01-21 08:34 UTC
### Steps to reproduce
1.
Force quit ownCloud App
2.
Restart ownCloud App
3.
Select demo.ownCloud.org Bookmark
4.
*Review Connection* alert is shown
5. 
Approve Certificate
6.
Repeat step 1-4, as a result, the *Review Connection* alert is shown again

### Expected behaviour
*Review Connection* alert should not shown again, after it was approved

### Actual behaviour
*Review Connection* alert is shown after every App start

### Client
**iOS version:**
12.1.2

**ownCloud app version:**
1.0 build 85 (5df9764)

**Device model:**
iPhone X

### Server configuration
**Web server:**
demo.owncloud.org

**Database:**

**PHP version:**

**ownCloud version:**

**Storage backend (external storage):**
demo.owncloud.org

#### ownCloud log (data/owncloud.log)
```
2019-01-21 09:29:26.561000+0100 ownCloud[35320.6572585] [info] | Show beta warning: Optional(true) [ServerListTableViewController.swift:118|MASKED]
2019-01-21 09:29:26.564000+0100 ownCloud[35320:6573842] [dbug] | Starting logging to /private/var/mobile/Containers/Shared/AppGroup/98D356CE-182F-42CF-AF3B-FF20D67A1ACD/ownCloudApp.log [OCLogFileWriter.m:84|MASKED]
2019-01-21 09:29:30.130000+0100 ownCloud[35352.6576530] [info] | ownCloud 1.0 (85) #5df9764 finished launching [AppDelegate.swift:33|FULL]
2019-01-21 09:29:30.131000+0100 ownCloud[35352:6576539] [dbug] | Starting logging to /private/var/mobile/Containers/Shared/AppGroup/98D356CE-182F-42CF-AF3B-FF20D67A1ACD/ownCloudApp.log [OCLogFileWriter.m:84|FULL]
2019-01-21 09:29:30.231000+0100 ownCloud[35352.6576530] [info] | Show beta warning: Optional(true) [ServerListTableViewController.swift:118|FULL]
2019-01-21 09:29:32.954000+0100 ownCloud[35352:6576541] [dbug] | ## Connection State changed to CONNECTING [OCConnection.m:161|FULL]
2019-01-21 09:29:32.956000+0100 ownCloud[35352:6576541] [dbug] | CQ[(null)]: saved request for taskIdentifier <1>, URL: <NSMutableURLRequest: 0x283de09e0> { URL: https://demo.owncloud.org/status.php }, 0x2814f92d0, 0x283fd1e40 [OCConnectionQueue.m:331|FULL]
2019-01-21 09:29:32.967000+0100 ownCloud[35352:6576542] [dbug] | Beginning activity 'update unstarted sets' .. [OCCore.m:1046|FULL]
2019-01-21 09:29:32.967000+0100 ownCloud[35352:6576542] [dbug] | Beginning activity 'update cache set' .. [OCCore.m:1046|FULL]
2019-01-21 09:29:32.967000+0100 ownCloud[35352:6576542] [dbug] | Beginning activity 'update retrieved set' .. [OCCore.m:1046|FULL]
2019-01-21 09:29:32.967000+0100 ownCloud[35352:6576542] [dbug] | Ended activity 'update unstarted sets' .. [OCCore.m:1059|FULL]
2019-01-21 09:29:32.970000+0100 ownCloud[35352:6576542] [dbug] | Cached Set(2): «private» [OCCore+ItemList.m:86|MASKED]
2019-01-21 09:29:32.970000+0100 ownCloud[35352:6576542] [dbug] | Retrieved Set(1): (null) [OCCore+ItemList.m:87|MASKED]
2019-01-21 09:29:32.970000+0100 ownCloud[35352:6576542] [dbug] | Beginning activity 'item list task' .. [OCCore.m:1046|MASKED]
2019-01-21 09:29:32.970000+0100 ownCloud[35352:6576542] [dbug] | Beginning activity 'item list task - update queries' .. [OCCore.m:1046|MASKED]
2019-01-21 09:29:32.970000+0100 ownCloud[35352:6576542] [dbug] | Ended activity 'item list task' .. [OCCore.m:1059|MASKED]
2019-01-21 09:29:32.970000+0100 ownCloud[35352:6576542] [dbug] | Ended activity 'update cache set' .. [OCCore.m:1059|MASKED]
2019-01-21 09:29:32.970000+0100 ownCloud[35352:6576542] [dbug] | Task root item: <OCItem: 0x2806f6bc0, type: 1, name: /, path: /, size: 5630922 bytes, MIME-Type: (null), Last modified: 2019-01-16 16:06:46 +0000, fileID: 00000015oc0ybqfryodg, eTag: "5c3f56968c5a9", parentID: (null)>, include root item: 0 [OCCore+ItemList.m:484|MASKED]
2019-01-21 09:29:32.971000+0100 ownCloud[35352:6576542] [dbug] | Ended activity 'item list task - update queries' .. [OCCore.m:1059|MASKED]
2019-01-21 09:29:33.326000+0100 ownCloud[35352:6576539] [dbug] | CQ[(null)]: «private»: «private» => protection space: «private» method: NSURLAuthenticationMethodServerTrust [OCConnectionQueue.m:744|MASKED]
2019-01-21 09:29:33.358000+0100 ownCloud[35352:6576541] [dbug] | CQ[(null)]: https://demo.owncloud.org/status.php [taskIdentifier=1]: didCompleteWithError=Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://demo.owncloud.org/status.php, NSErrorFailingURLKey=https://demo.owncloud.org/status.php, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <DD435A57-9975-4CEF-947A-1CE75F5B8D36>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <DD435A57-9975-4CEF-947A-1CE75F5B8D36>.<1>, NSLocalizedDescription=cancelled} [OCConnectionQueue.m:615|MASKED]
2019-01-21 09:29:33.359000+0100 ownCloud[35352:6576540] [dbug] | ## Connection State changed to DISCONNECTED [OCConnection.m:165|MASKED]
2019-01-21 09:29:33.359000+0100 ownCloud[35352:6576540] [dbug] | CQ[(null)]: Removing request «private» with taskIdentifier <1> [OCConnectionQueue.m:541|MASKED]
2019-01-21 09:29:33.359000+0100 ownCloud[35352:6576583] [dbug] | ## Connection State changed to CONNECTING [OCConnection.m:161|MASKED]
2019-01-21 09:29:33.361000+0100 ownCloud[35352:6576583] [dbug] | CQ[(null)]: saved request for taskIdentifier <2>, URL: <NSMutableURLRequest: 0x283dec200> { URL: https://demo.owncloud.org/status.php }, 0x2814f92d0, 0x283fd1e40 [OCConnectionQueue.m:331|MASKED]
2019-01-21 09:29:33.469000+0100 ownCloud[35352:6576541] [dbug] | CQ[(null)]: «private»: «private» => protection space: «private» method: NSURLAuthenticationMethodServerTrust [OCConnectionQueue.m:744|MASKED]
2019-01-21 09:29:33.489000+0100 ownCloud[35352:6576541] [dbug] | CQ[(null)]: https://demo.owncloud.org/status.php [taskIdentifier=2]: didCompleteWithError=Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://demo.owncloud.org/status.php, NSErrorFailingURLKey=https://demo.owncloud.org/status.php, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <7C28DA3C-8DE1-42F5-B889-C8EBC3D41DB4>.<2>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <7C28DA3C-8DE1-42F5-B889-C8EBC3D41DB4>.<2>, NSLocalizedDescription=cancelled} [OCConnectionQueue.m:615|MASKED]
2019-01-21 09:29:33.490000+0100 ownCloud[35352:6576542] [dbug] | ## Connection State changed to DISCONNECTED [OCConnection.m:165|MASKED]
2019-01-21 09:29:33.490000+0100 ownCloud[35352:6576542] [dbug] | CQ[(null)]: Removing request «private» with taskIdentifier <2> [OCConnectionQueue.m:541|MASKED]
2019-01-21 09:29:33.492000+0100 ownCloud[35352:6576541] [dbug] | CQ[(null)]: saved request for taskIdentifier <3>, URL: <NSMutableURLRequest: 0x283df8380> { URL: https://demo.owncloud.org/remote.php/dav/files/ }, 0x2814f92d0, 0x283fd1e40 [OCConnectionQueue.m:331|MASKED]
2019-01-21 09:29:33.595000+0100 ownCloud[35352:6576542] [dbug] | CQ[(null)]: «private»: «private» => protection space: «private» method: NSURLAuthenticationMethodServerTrust [OCConnectionQueue.m:744|MASKED]
2019-01-21 09:29:34.232000+0100 ownCloud[35352:6576539] [dbug] | CQ[(null)]: https://demo.owncloud.org/remote.php/dav/files/ [taskIdentifier=3]: didCompleteWithError=(null) [OCConnectionQueue.m:615|MASKED]
2019-01-21 09:29:34.234000+0100 ownCloud[35352:6576541] [dbug] | Error: Error Domain=OCHTTPStatusErrorDomain Code=405 "(null)" - Response: <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\MethodNotAllowed</s:exception>
  <s:message>Listing members of this collection is disabled</s:message>
</d:error>
 [OCConnection.m:632|MASKED]
2019-01-21 09:29:34.236000+0100 ownCloud[35352:6576541] [dbug] | CQ[(null)]: Removing request «private» with taskIdentifier <3> [OCConnectionQueue.m:541|MASKED]
2019-01-21 09:29:34.236000+0100 ownCloud[35352:6576539] [dbug] | Cached Set(2): «private» [OCCore+ItemList.m:86|MASKED]
2019-01-21 09:29:34.236000+0100 ownCloud[35352:6576539] [dbug] | Retrieved Set(3): (null) [OCCore+ItemList.m:87|MASKED]
2019-01-21 09:29:34.236000+0100 ownCloud[35352:6576539] [dbug] | Beginning activity 'item list task' .. [OCCore.m:1046|MASKED]
2019-01-21 09:29:34.236000+0100 ownCloud[35352:6576539] [dbug] | Beginning activity 'item list task - update queries' .. [OCCore.m:1046|MASKED]
2019-01-21 09:29:34.236000+0100 ownCloud[35352:6576539] [dbug] | Ended activity 'item list task' .. [OCCore.m:1059|MASKED]
2019-01-21 09:29:34.236000+0100 ownCloud[35352:6576539] [dbug] | Ended activity 'update retrieved set' .. [OCCore.m:1059|MASKED]
2019-01-21 09:29:34.236000+0100 ownCloud[35352:6576539] [dbug] | Task root item: <OCItem: 0x2806f6bc0, type: 1, name: /, path: /, size: 5630922 bytes, MIME-Type: (null), Last modified: 2019-01-16 16:06:46 +0000, fileID: 00000015oc0ybqfryodg, eTag: "5c3f56968c5a9", parentID: (null)>, include root item: 0 [OCCore+ItemList.m:484|MASKED]
2019-01-21 09:29:34.237000+0100 ownCloud[35352:6576539] [dbug] | Ended activity 'item list task - update queries' .. [OCCore.m:1059|MASKED]
2019-01-21 09:29:34.261000+0100 ownCloud[35352:6576539] [dbug] | CQ[(null)]: saved request for taskIdentifier <4>, URL: <NSMutableURLRequest: 0x283df86e0> { URL: https://demo.owncloud.org/remote.php/dav/files/ownCloud%20Manual.pdf?y=180&preview=1&x=180&c=%22c6cce681d5becb1ed82fa1cc177a7e09%22&a=1 }, 0x2814f92d0, 0x283fd1e40 [OCConnectionQueue.m:331|MASKED]
2019-01-21 09:29:34.529000+0100 ownCloud[35352:6576542] [dbug] | CQ[(null)]: https://demo.owncloud.org/remote.php/dav/files/ownCloud%20Manual.pdf?y=180&preview=1&x=180&c=%22c6cce681d5becb1ed82fa1cc177a7e09%22&a=1 [taskIdentifier=4]: didCompleteWithError=(null) [OCConnectionQueue.m:615|MASKED]
2019-01-21 09:29:34.529000+0100 ownCloud[35352:6576583] [dbug] | Beginning activity 'Handling event' .. [OCCore.m:1046|MASKED]
2019-01-21 09:29:34.530000+0100 ownCloud[35352:6576542] [dbug] | Ended activity 'Handling event' .. [OCCore.m:1059|MASKED]
2019-01-21 09:29:34.530000+0100 ownCloud[35352:6576583] [dbug] | CQ[(null)]: Removing request «private» with taskIdentifier <4> [OCConnectionQueue.m:541|MASKED]
2019-01-21 09:29:41.874000+0100 ownCloud[35353.6576686] [info] | ownCloud 1.0 (85) #5df9764 finished launching [AppDelegate.swift:33|FULL]
2019-01-21 09:29:41.875000+0100 ownCloud[35353:6576696] [dbug] | Starting logging to /private/var/mobile/Containers/Shared/AppGroup/98D356CE-182F-42CF-AF3B-FF20D67A1ACD/ownCloudApp.log [OCLogFileWriter.m:84|FULL]
2019-01-21 09:29:41.963000+0100 ownCloud[35353.6576686] [info] | Show beta warning: Optional(true) [ServerListTableViewController.swift:118|FULL]
2019-01-21 09:29:44.715000+0100 ownCloud[35353:6576696] [dbug] | ## Connection State changed to CONNECTING [OCConnection.m:161|FULL]
2019-01-21 09:29:44.717000+0100 ownCloud[35353:6576696] [dbug] | CQ[(null)]: saved request for taskIdentifier <1>, URL: <NSMutableURLRequest: 0x281124140> { URL: https://demo.owncloud.org/status.php }, 0x283839880, 0x281328720 [OCConnectionQueue.m:331|FULL]
2019-01-21 09:29:44.729000+0100 ownCloud[35353:6576696] [dbug] | Beginning activity 'update unstarted sets' .. [OCCore.m:1046|FULL]
2019-01-21 09:29:44.729000+0100 ownCloud[35353:6576696] [dbug] | Beginning activity 'update cache set' .. [OCCore.m:1046|FULL]
2019-01-21 09:29:44.729000+0100 ownCloud[35353:6576696] [dbug] | Beginning activity 'update retrieved set' .. [OCCore.m:1046|FULL]
2019-01-21 09:29:44.729000+0100 ownCloud[35353:6576696] [dbug] | Ended activity 'update unstarted sets' .. [OCCore.m:1059|FULL]
2019-01-21 09:29:44.732000+0100 ownCloud[35353:6576699] [dbug] | Cached Set(2): «private» [OCCore+ItemList.m:86|MASKED]
2019-01-21 09:29:44.732000+0100 ownCloud[35353:6576699] [dbug] | Retrieved Set(1): (null) [OCCore+ItemList.m:87|MASKED]
2019-01-21 09:29:44.732000+0100 ownCloud[35353:6576699] [dbug] | Beginning activity 'item list task' .. [OCCore.m:1046|MASKED]
2019-01-21 09:29:44.732000+0100 ownCloud[35353:6576699] [dbug] | Beginning activity 'item list task - update queries' .. [OCCore.m:1046|MASKED]
2019-01-21 09:29:44.732000+0100 ownCloud[35353:6576699] [dbug] | Ended activity 'item list task' .. [OCCore.m:1059|MASKED]
2019-01-21 09:29:44.732000+0100 ownCloud[35353:6576699] [dbug] | Ended activity 'update cache set' .. [OCCore.m:1059|MASKED]
2019-01-21 09:29:44.732000+0100 ownCloud[35353:6576699] [dbug] | Task root item: <OCItem: 0x282a22680, type: 1, name: /, path: /, size: 5630922 bytes, MIME-Type: (null), Last modified: 2019-01-16 16:06:46 +0000, fileID: 00000015oc0ybqfryodg, eTag: "5c3f56968c5a9", parentID: (null)>, include root item: 0 [OCCore+ItemList.m:484|MASKED]
2019-01-21 09:29:44.733000+0100 ownCloud[35353:6576699] [dbug] | Ended activity 'item list task - update queries' .. [OCCore.m:1059|MASKED]
2019-01-21 09:29:45.227000+0100 ownCloud[35353:6576699] [dbug] | CQ[(null)]: «private»: «private» => protection space: «private» method: NSURLAuthenticationMethodServerTrust [OCConnectionQueue.m:744|MASKED]
2019-01-21 09:29:45.254000+0100 ownCloud[35353:6576696] [dbug] | CQ[(null)]: https://demo.owncloud.org/status.php [taskIdentifier=1]: didCompleteWithError=Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://demo.owncloud.org/status.php, NSErrorFailingURLKey=https://demo.owncloud.org/status.php, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <0A9E05D4-CA14-4979-8341-E64E4BCF39FF>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <0A9E05D4-CA14-4979-8341-E64E4BCF39FF>.<1>, NSLocalizedDescription=cancelled} [OCConnectionQueue.m:615|MASKED]
2019-01-21 09:29:45.254000+0100 ownCloud[35353:6576699] [dbug] | ## Connection State changed to DISCONNECTED [OCConnection.m:165|MASKED]
2019-01-21 09:29:45.254000+0100 ownCloud[35353:6576699] [dbug] | CQ[(null)]: Removing request «private» with taskIdentifier <1> [OCConnectionQueue.m:541|MASKED]
2019-01-21 09:29:45.255000+0100 ownCloud[35353:6576699] [dbug] | ## Connection State changed to CONNECTING [OCConnection.m:161|MASKED]
2019-01-21 09:29:45.257000+0100 ownCloud[35353:6576699] [dbug] | CQ[(null)]: saved request for taskIdentifier <2>, URL: <NSMutableURLRequest: 0x281120540> { URL: https://demo.owncloud.org/status.php }, 0x283839880, 0x281328720 [OCConnectionQueue.m:331|MASKED]
2019-01-21 09:29:45.435000+0100 ownCloud[35353:6576698] [dbug] | CQ[(null)]: «private»: «private» => protection space: «private» method: NSURLAuthenticationMethodServerTrust [OCConnectionQueue.m:744|MASKED]
2019-01-21 09:29:45.451000+0100 ownCloud[35353:6576699] [dbug] | CQ[(null)]: https://demo.owncloud.org/status.php [taskIdentifier=2]: didCompleteWithError=Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://demo.owncloud.org/status.php, NSErrorFailingURLKey=https://demo.owncloud.org/status.php, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <14AEFD1F-B36E-48A5-88F2-12900B955EF8>.<2>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <14AEFD1F-B36E-48A5-88F2-12900B955EF8>.<2>, NSLocalizedDescription=cancelled} [OCConnectionQueue.m:615|MASKED]
2019-01-21 09:29:45.451000+0100 ownCloud[35353:6576736] [dbug] | ## Connection State changed to DISCONNECTED [OCConnection.m:165|MASKED]
2019-01-21 09:29:45.451000+0100 ownCloud[35353:6576736] [dbug] | CQ[(null)]: Removing request «private» with taskIdentifier <2> [OCConnectionQueue.m:541|MASKED]
2019-01-21 09:29:45.454000+0100 ownCloud[35353:6576698] [dbug] | CQ[(null)]: saved request for taskIdentifier <3>, URL: <NSMutableURLRequest: 0x281124570> { URL: https://demo.owncloud.org/remote.php/dav/files/ }, 0x283839880, 0x281328720 [OCConnectionQueue.m:331|MASKED]
2019-01-21 09:29:45.563000+0100 ownCloud[35353:6576699] [dbug] | CQ[(null)]: «private»: «private» => protection space: «private» method: NSURLAuthenticationMethodServerTrust [OCConnectionQueue.m:744|MASKED]
2019-01-21 09:29:46.130000+0100 ownCloud[35353:6576736] [dbug] | CQ[(null)]: https://demo.owncloud.org/remote.php/dav/files/ [taskIdentifier=3]: didCompleteWithError=(null) [OCConnectionQueue.m:615|MASKED]
2019-01-21 09:29:46.131000+0100 ownCloud[35353:6576699] [dbug] | Error: Error Domain=OCHTTPStatusErrorDomain Code=405 "(null)" - Response: <?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\MethodNotAllowed</s:exception>
  <s:message>Listing members of this collection is disabled</s:message>
</d:error>
 [OCConnection.m:632|MASKED]
2019-01-21 09:29:46.132000+0100 ownCloud[35353:6576699] [dbug] | CQ[(null)]: Removing request «private» with taskIdentifier <3> [OCConnectionQueue.m:541|MASKED]
2019-01-21 09:29:46.132000+0100 ownCloud[35353:6576698] [dbug] | Cached Set(2): «private» [OCCore+ItemList.m:86|MASKED]
2019-01-21 09:29:46.132000+0100 ownCloud[35353:6576698] [dbug] | Retrieved Set(3): (null) [OCCore+ItemList.m:87|MASKED]
2019-01-21 09:29:46.132000+0100 ownCloud[35353:6576698] [dbug] | Beginning activity 'item list task' .. [OCCore.m:1046|MASKED]
2019-01-21 09:29:46.132000+0100 ownCloud[35353:6576698] [dbug] | Beginning activity 'item list task - update queries' .. [OCCore.m:1046|MASKED]
2019-01-21 09:29:46.132000+0100 ownCloud[35353:6576698] [dbug] | Ended activity 'item list task' .. [OCCore.m:1059|MASKED]
2019-01-21 09:29:46.132000+0100 ownCloud[35353:6576698] [dbug] | Ended activity 'update retrieved set' .. [OCCore.m:1059|MASKED]
2019-01-21 09:29:46.132000+0100 ownCloud[35353:6576698] [dbug] | Task root item: <OCItem: 0x282a22680, type: 1, name: /, path: /, size: 5630922 bytes, MIME-Type: (null), Last modified: 2019-01-16 16:06:46 +0000, fileID: 00000015oc0ybqfryodg, eTag: "5c3f56968c5a9", parentID: (null)>, include root item: 0 [OCCore+ItemList.m:484|MASKED]
2019-01-21 09:29:46.133000+0100 ownCloud[35353:6576698] [dbug] | Ended activity 'item list task - update queries' .. [OCCore.m:1059|MASKED]
2019-01-21 09:29:46.153000+0100 ownCloud[35353:6576699] [dbug] | CQ[(null)]: saved request for taskIdentifier <4>, URL: <NSMutableURLRequest: 0x281124c60> { URL: https://demo.owncloud.org/remote.php/dav/files/ownCloud%20Manual.pdf?y=180&preview=1&x=180&c=%22c6cce681d5becb1ed82fa1cc177a7e09%22&a=1 }, 0x283839880, 0x281328720 [OCConnectionQueue.m:331|MASKED]
2019-01-21 09:29:46.743000+0100 ownCloud[35353:6576699] [dbug] | CQ[(null)]: https://demo.owncloud.org/remote.php/dav/files/ownCloud%20Manual.pdf?y=180&preview=1&x=180&c=%22c6cce681d5becb1ed82fa1cc177a7e09%22&a=1 [taskIdentifier=4]: didCompleteWithError=(null) [OCConnectionQueue.m:615|MASKED]
2019-01-21 09:29:46.744000+0100 ownCloud[35353:6576697] [dbug] | Beginning activity 'Handling event' .. [OCCore.m:1046|MASKED]
2019-01-21 09:29:46.744000+0100 ownCloud[35353:6576697] [dbug] | CQ[(null)]: Removing request «private» with taskIdentifier <4> [OCConnectionQueue.m:541|MASKED]
2019-01-21 09:29:46.744000+0100 ownCloud[35353:6576698] [dbug] | Ended activity 'Handling event' .. [OCCore.m:1059|MASKED]
2019-01-21 09:29:50.786000+0100 ownCloud[35353.6576686] [info] | Show beta warning: Optional(true) [ServerListTableViewController.swift:118|MASKED]
2019-01-21 09:29:50.787000+0100 ownCloud[35353:6576699] [dbug] | ## Connection State changed to DISCONNECTED [OCConnection.m:165|MASKED]
2019-01-21 09:29:50.788000+0100 ownCloud[35353:6576699] [dbug] | CQ[(null)]: finish tasks and invalidate [OCConnectionQueue.m:112|MASKED]
2019-01-21 09:29:50.788000+0100 ownCloud[35353:6576699] [dbug] | CQ[F1D6381F-34E5-4883-A9F3-7AD0B3CD51FA;com.owncloud.ios-app]: finish tasks and invalidate [OCConnectionQueue.m:112|MASKED]
2019-01-21 09:29:50.789000+0100 ownCloud[35353:6576697] [dbug] | CQ[(null)]: did become invalid, running completionHandler 0x281d7d2c0 [OCConnectionQueue.m:700|MASKED]
2019-01-21 09:29:50.793000+0100 ownCloud[35353:6576699] [dbug] | CQ[F1D6381F-34E5-4883-A9F3-7AD0B3CD51FA;com.owncloud.ios-app]: did become invalid, running completionHandler 0x281d77a80 [OCConnectionQueue.m:700|MASKED]
```

![img_603df195370f-1](https://user-images.githubusercontent.com/736109/51461786-5106a780-1d5f-11e9-8937-65320a9a933b.jpeg)

**Comment by pablocarmu** [comment] 2019-01-21 09:23
I've downloaded the latest ownCloud beta from Testflight and it's
`ownCloud beta version 1.0 build 98 (63df379)`

With _build 98_ version I can't reproduce the error, could you update your app and see if you can reproduce it?

**Comment by hosy** [comment] 2019-01-21 09:36
@pablocarmu No, I have the same issue in `ownCloud beta version 1.0 build 98 (63df379)`
@jesmrec This entry is missing for me
![img_9bb304b23398-1](https://user-images.githubusercontent.com/736109/51465499-52889d80-1d68-11e9-8fc7-ed9e53fd0881.jpeg)

**Comment by hosy** [comment] 2019-01-21 09:42
On the iPad 12.9 iOS 12.1.1 I do not get this approval alert. Furthermore I cannot see a certificate entry in the settings.

**Comment by felix-schwarz** [comment] 2019-01-28 23:37
Chances are the app's keychain on that device is corrupted. I'll add additional logging to the keychain in a future SDK version to see what/if errors occur.

**Comment by felix-schwarz** [comment] 2019-01-30 16:31
Should be addressed by https://github.com/owncloud/ios-app/commit/f5e1784a32231b8ca96f1e415a757967dd018478 in `fp-series-3`.

**Comment by jesmrec** [comment] 2019-01-31 09:39
from my side was not reproducible. @hosy, could you take a look if the problem is fixed?

**Comment by hosy** [comment] 2019-01-31 09:42
Problem ist fixed with this commit @jesmrec

**Comment by jesmrec** [comment] 2019-01-31 10:59
Perfect, thanks everyone!

**Closed by jesmrec** 2019-01-31 10:59 UTC
Labels: bug, fixed-in-branch, p3-medium
